// Code generated by "stringer -type=HttpMethod"; DO NOT EDIT.

package proxy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GET-0]
	_ = x[HEAD-1]
	_ = x[POST-2]
	_ = x[PUT-3]
	_ = x[DELETE-4]
	_ = x[CONNECT-5]
	_ = x[OPTIONS-6]
	_ = x[TRACE-7]
	_ = x[PATCH-8]
}

const _HttpMethod_name = "GETHEADPOSTPUTDELETECONNECTOPTIONSTRACEPATCH"

var _HttpMethod_index = [...]uint8{0, 3, 7, 11, 14, 20, 27, 34, 39, 44}

func (i HttpMethod) String() string {
	if i < 0 || i >= HttpMethod(len(_HttpMethod_index)-1) {
		return "HttpMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HttpMethod_name[_HttpMethod_index[i]:_HttpMethod_index[i+1]]
}
