name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --branch "${{ github.head_ref || github.ref_name }}" "https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git" .
      - run: go test ./...
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --branch "${{ github.head_ref || github.ref_name }}" "https://oauth2:${{ github.token }}@github.com/${{ github.repository }}.git" .
      - run: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run
